### ISSUE TITLE
add `ignoreValues` (for values like -1?)

### ISSUE THREAD

**Issue by certainlyakey** [niksy/stylelint-number-z-index-constraint#3]
Even when maintaining sane z-index order, occasionally you need `z-index:-1` for putting something under the z-index-less content. Would you consider adding an ignore parameter so that stylelint won't complain about those when we have minimal level set? 

Thanks!

**Comment by kristerkari** [comment]
As there hasn't been any activity in this repo for 2 years, I created a new plugin that has updated dependencies and implements secondary `ignoreValues` option.

@certainlyakey have a look at my fork of this plugin:
https://github.com/kristerkari/stylelint-z-index-value-constraint

**Comment by certainlyakey** [comment]
Thanks @kristerkari!

**Comment by niksy** [comment]
Sorry for replying this late @certainlyakey ! Does the version from @kristerkari helps you? I can apply changes here if you’re both interested so we can have one option.
